# Generated by Django 6.0.4 on 2026-05-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
