# Generated by Django 6.0.4 on 2026-05-05 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='customer_name',
        ),
    ]
