# Generated by Django 6.0.4 on 2026-05-05 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cashnova_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='English', max_length=50)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=80)),
                ('email_notifications', models.BooleanField(default=True)),
                ('ai_prediction_alerts', models.BooleanField(default=True)),
                ('monthly_report_reminder', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cashnova_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
