# Generated by Django 6.0.4 on 2026-05-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
